<?php

namespace App\Filament\Resources\ClaimResource\RelationManagers;

use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Actions\ViewAction;
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\BadgeColumn;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Filters\SelectFilter;

/**
 * Claim Steps Relation Manager
 *
 * Note: Admins can only view claim steps. Create, edit, and delete actions are disabled
 * because claim steps are automatically generated by the system during the claim workflow:
 * - Step 1: Claim approved
 * - Step 2: Claim paid
 * - Step 3: Claim in progress
 * - Step 4: Claim delivered
 */
class ClaimStepsRelationManager extends RelationManager
{
    protected static string $relationship = 'claimSteps';

    protected static ?string $recordTitleAttribute = 'description';

    protected static ?string $title = 'مراحل درخواست';

    protected static ?string $modelLabel = 'مرحله درخواست';

    protected static ?string $pluralModelLabel = 'مراحل درخواست';

    public function getTableRecordKey($record): string
    {
        return $record->claim_id . '_' . $record->step_id;
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('step_id')
                    ->label(__('site.step_id'))
                    ->numeric()
                    ->required(),
                Forms\Components\Textarea::make('description')
                    ->label(__('site.description'))
                    ->required()
                    ->rows(3)
                    ->maxLength(1000),
                Forms\Components\Textarea::make('data')
                    ->label(__('site.data'))
                    ->rows(3)
                    ->maxLength(1000),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('id')
                    ->label(__('site.table_id'))
                    ->sortable()
                    ->searchable(),
                TextColumn::make('step_id')
                    ->label(__('site.step_id'))
                    ->sortable()
                    ->searchable()
                    ->badge()
                    ->color('primary'),
                TextColumn::make('description')
                    ->label(__('site.description'))
                    ->searchable()
                    ->limit(100)
                    ->wrap(),
                TextColumn::make('created_at')
                    ->label(__('site.created_at'))
                    ->dateTime('Y/m/d H:i')
                    ->sortable(),
            ])
            ->filters([
                SelectFilter::make('step_id')
                    ->label(__('site.step_id'))
                    ->options(function () {
                        $steps = \Domain\Claim\Models\ClaimStep::distinct('step_id')->pluck('step_id', 'step_id');
                        return $steps->mapWithKeys(function ($stepId) {
                            return [$stepId => __('site.step') . ' ' . $stepId];
                        });
                    }),
            ])
            ->actions([
                // ViewAction::make()
                //     ->label(__('site.view_claim_step')),
            ])
            ->defaultSort('created_at', 'desc');
    }
}
